services:
  - type: web
    name: bloc_note
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bloc_note.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bloc_note.settings
