# Generated by Django 5.2.5 on 2025-10-12 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('Etudes', 'Etudes'), ('Projets', 'Projets'), ('Reunion', 'Réunion'), ('Autres', 'Autres')], default='Autres', max_length=50)),
                ('contenu', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'mp4', 'mp3', 'jpg', 'png', 'jpeg'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
