# Generated by Django 5.2.5 on 2025-11-21 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='notes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'mp4', 'mp3', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
